export const aboutMe = {
  name: "Amer Albadawi",
  brief: "",
  profilePic: "/images/amer-pic.png",
  // flagUrl: "/images/jordan-flag.png",
  // flagUrl: "/images/japan-flag.png",
  lastWord: "",
} as const;

export const typeWriteList = [
  "Digital Transformations.",
  "Client Acceleration.",
  "Innovative Future.",
  "Digital Excellence.",
  "Solution Transformations.",
  "Technology Empowerment.",
  "Creative Coding.",
  "Progressive Code.",
  "Digital Shaping.",
  "Dream Engineering.",
  "Growth Catalyst.",
  "Speed Innovation.",
  "Excellence Core.",
  "Tomorrow’s Code.",
  "Innovation Barriers.",
  "Tech Crafting.",
  "Purpose Technology.",
  "Industry Revolution.",
  "Vision Empowerment.",
  "Smarter Coding.",
  "Digital Agility.",
  "Dream Bridging.",
  "Innovate Accelerate.",
  "Bridge Success.",
  "Masterpiece Transformation.",
  "Business Elevation.",
  "Connected Coding.",
  "Vision Victories.",
  "Innovation Empowerment.",
  "Design Dominate.",
  "Innovation Pioneering.",
  "Digital Unleashing.",
  "Click Crafting.",
  "Tech Navigation.",
  "Byte Excellence.",
  "Result Transformation.",
  "Tomorrow Innovation.",
  "Digital Dreams.",
  "Revolution Solutions.",
  "Digital Gateway.",
  "Future Code.",
  "Digital Life.",
  "Precision Innovation.",
  "World Connectivity.",
  "Digital Trails.",
  "Tech Reality.",
  "Craftsmanship Future.",
  "Impact Innovation.",
  "Futures Coding.",
  "Human Tech.",
  "Landscape Engineering.",
  "Innovation Architects.",
  "Divide Bridging.",
  "Future Focused.",
  "Digital Partners.",
  "Journey Empowerment.",
  "Create Conquer.",
  "Extraordinary Tech.",
  "Charge Leadership.",
  "Connected Crafting.",
];
