#!/bin/sh
. "$(dirname "$0")/_/husky.sh" # If using Husky

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

nvm use 20 # Or nvm use if you use .nvmrc

npm run test # Or yarn test, pnpm test
# Or your test command directly